dataset: "multisweep"
vcf_file: "resources/data/multiple_sweeps/GHIST_2025_multisweep.15.final.vcf.gz"
chromosome: "15"

# Tajima's D parameters
window_size: []
step_size_ratio: []

moving_window_size: [25, 50, 100]
moving_step_size_ratio: [1]

cutoff: [0.05]
winsize: []
