dataset: "singlesweep"
vcf_file: "resources/data/single_sweep/GHIST_2025_singlesweep.21.testing.vcf.gz"
chromosome: "21"

# Tajima's D parameters
window_size: [50_000, 60_000, 70_000 ,100_000]
step_size_ratio: [0.01, 0.1, 0.3, 0.5, 0.6, 1]

moving_window_size: [100]
moving_step_size_ratio: [0.5, 1]

cutoff: 0.005
winsize: [100_000, 500_000, 1_000_000]

